### ISSUE TITLE
Gather notebooks from Feb 2019 Hack Day

### ISSUE THREAD

**Issue by pllim** [spacetelescope/dat_pyinthesky#5]
Teams:

- [x] @SaOgaz, @ivastar, @kassin -- MOS Spec of xgal fields, #3
- [x] @hcferguson, @stscicrawford -- Sky Fitting/Subtraction, #4 and #6
- [x] @drdavella -- ASDF tree viz, #2
- [x] @javerbukh, Nora Luetzgendorf, @brechmos-stsci -- IFU... something, #10 
- [ ] @nmearl, Gisella de Rosa -- Estimate the z and BH mass of a high-z QSO from NIRSPEC long-slit spectrum
- [x] @pllim, @mcorrenti, @eteq -- Crowded field imaging, #7 
- [x] @tddesjardins, @havok2063 -- Molecular abundance retrieval (+archive access), #8 

Thank you for your participation in the Hack Day! If you are mentioned here and haven't done so already, please submit your notebook as a pull request to this repository ASAP. If you have submitted a PR, thank you!

The notebook does not have to work; i.e., there is no CI hooked up to this repo to run them. We just need them so we have a record of what was done. If you could add some commentary to the notebooks on what worked for you and what could be improved, it would be greatly appreciated.

**Comment by pllim** [comment]
p.s. If you know the GitHub username for some of the people above, please let me know too.

**Comment by pllim** [comment]
p.p.s. Please ensure there is no sensitive data in your notebook before you open a pull request. Do not include sensitive data files!
